/**
 * NanoSami — AI Assistance layer, CORE part (v0.4.0).
 *
 * Boundaries (docs/AI.md):
 *  - NanoSami's deterministic engines produce all numbers. The AI layer only
 *    EXPLAINS; it never computes or modifies experimental data.
 *  - This module is pure: it builds structured context text and provider
 *    request payloads. It performs no network calls and stores no secrets —
 *    those concerns live in the UI layer with explicit user consent.
 *  - App must work fully with AI disabled/offline (verified by tests).
 */

/**
 * Build a structured, human-readable analysis context for an AI assistant.
 * Everything is labelled by origin: measured data / NanoSami-calculated /
 * user assumption / known limitation.
 * @param {object} ctx
 * @param {string} ctx.analysisType   e.g. 'XRD pattern analysis'
 * @param {string} [ctx.sampleName]
 * @param {string} [ctx.appVersion]
 * @param {object} [ctx.settings]     calculation/detection settings (key→value)
 * @param {string[]} [ctx.units]      e.g. ['2θ in degrees', 'd in Å']
 * @param {string[]} [ctx.assumptions]
 * @param {{columns:string[], rows:any[][], origin:string}[]} [ctx.tables]
 * @param {object} [ctx.results]      key numeric results (NanoSami-calculated)
 * @param {string[]} [ctx.limitations]
 */
export function buildAnalysisContext(ctx) {
  if (!ctx || !ctx.analysisType) throw new Error('analysisType is required.');
  const L = [];
  L.push(`# NanoSami analysis context`);
  L.push(`Generated by NanoSami ${ctx.appVersion || ''} — a deterministic, offline nanomaterials analysis tool. All numbers below were computed by NanoSami's validated routines or come directly from the user's measured data; none were AI-generated.`);
  L.push('');
  L.push(`Analysis type: ${ctx.analysisType}`);
  if (ctx.sampleName) L.push(`Sample: ${ctx.sampleName}`);
  if (ctx.units?.length) L.push(`Units: ${ctx.units.join('; ')}`);
  if (ctx.settings && Object.keys(ctx.settings).length) {
    L.push('', '## Settings (user-selected)');
    for (const [k, v] of Object.entries(ctx.settings)) L.push(`- ${k}: ${v}`);
  }
  if (ctx.assumptions?.length) {
    L.push('', '## Assumptions (user-selected or method-inherent)');
    ctx.assumptions.forEach((a) => L.push(`- ${a}`));
  }
  for (const t of ctx.tables || []) {
    L.push('', `## Table (${t.origin})`);
    L.push(t.columns.join(' | '));
    L.push(t.columns.map(() => '---').join(' | '));
    for (const row of t.rows) L.push(row.map((c) => (c === null || c === undefined ? '—' : String(c))).join(' | '));
  }
  if (ctx.results && Object.keys(ctx.results).length) {
    L.push('', '## Key results (NanoSami-calculated)');
    for (const [k, v] of Object.entries(ctx.results)) L.push(`- ${k}: ${v}`);
  }
  if (ctx.limitations?.length) {
    L.push('', '## Known limitations');
    ctx.limitations.forEach((a) => L.push(`- ${a}`));
  }
  return L.join('\n');
}

/** Wrap a context + user question into a copy-ready prompt for any assistant. */
export function buildPrompt(context, question) {
  const q = (question || '').trim() || 'Please explain these results to a materials-science student, including what can and cannot be concluded from them.';
  return `${context}\n\n## Question\n${q}\n\nPlease: (1) distinguish clearly between what the data show and what is interpretation, (2) state uncertainty honestly, (3) do not invent reference values.`;
}

/**
 * MODE A — external chat services. We only OPEN the service; where a public
 * URL-prefill parameter exists it is attempted, but the prompt is always
 * copied to the clipboard first because prefill support can change at any
 * time and is not an official integration. No accounts, no passwords.
 */
export const EXTERNAL_SERVICES = [
  { id: 'chatgpt', label: 'ChatGPT', baseUrl: 'https://chatgpt.com/', prefillParam: 'q', prefillReliable: false },
  { id: 'claude', label: 'Claude', baseUrl: 'https://claude.ai/new', prefillParam: 'q', prefillReliable: false },
  { id: 'gemini', label: 'Gemini', baseUrl: 'https://gemini.google.com/app', prefillParam: null, prefillReliable: false },
  { id: 'grok', label: 'Grok', baseUrl: 'https://grok.com/', prefillParam: null, prefillReliable: false },
];

const MAX_URL_PROMPT = 4000; // conservative; long prompts must go via clipboard

export function buildExternalOpen(serviceId, prompt) {
  const s = EXTERNAL_SERVICES.find((x) => x.id === serviceId);
  if (!s) throw new Error(`Unknown service "${serviceId}".`);
  let url = s.baseUrl;
  let prefilled = false;
  if (s.prefillParam && prompt && prompt.length <= MAX_URL_PROMPT) {
    const u = new URL(s.baseUrl);
    u.searchParams.set(s.prefillParam, prompt);
    url = u.toString();
    prefilled = true;
  }
  return {
    url, prefilled, label: s.label,
    note: prefilled
      ? 'The prompt was copied to your clipboard and passed in the URL. If the chat opens empty, just paste (Ctrl/Cmd+V) — URL prefill is not officially guaranteed by the provider.'
      : 'The prompt was copied to your clipboard. Paste it (Ctrl/Cmd+V) into the chat after it opens.',
  };
}

/**
 * MODE B — bring-your-own-API request builders. Pure: they return
 * {url, headers, body} for fetch performed by the UI layer. Keys are passed in
 * per call and never stored here.
 */
export const API_PROVIDERS = [
  { id: 'anthropic', label: 'Anthropic (Claude API)', keyHint: 'sk-ant-…', docs: 'https://docs.claude.com' },
  { id: 'openai', label: 'OpenAI (API)', keyHint: 'sk-…', docs: 'https://platform.openai.com/docs' },
  { id: 'openai-compatible', label: 'OpenAI-compatible endpoint (custom URL)', keyHint: 'provider key', docs: null },
];

export function buildApiRequest({ provider, apiKey, model, prompt, baseUrl = null, maxTokens = 1024 }) {
  if (!apiKey || typeof apiKey !== 'string' || apiKey.trim().length < 8) throw new Error('A valid API key is required.');
  if (!prompt) throw new Error('Prompt is empty.');
  const system = 'You are an assistant inside NanoSami, a deterministic nanomaterials analysis tool. Explain the provided analysis cautiously. Never invent reference values or claim definitive phase/material identification. Distinguish measured data, NanoSami-calculated results, and your own interpretation. Any processing you suggest is only a suggestion the user must apply themselves in NanoSami.';
  if (provider === 'anthropic') {
    return {
      url: 'https://api.anthropic.com/v1/messages',
      headers: {
        'content-type': 'application/json',
        'x-api-key': apiKey.trim(),
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({
        model: model || 'claude-sonnet-4-6',
        max_tokens: maxTokens,
        system,
        messages: [{ role: 'user', content: prompt }],
      }),
      extractText: (json) => (json.content || []).filter((b) => b.type === 'text').map((b) => b.text).join('\n'),
    };
  }
  if (provider === 'openai' || provider === 'openai-compatible') {
    const url = provider === 'openai' ? 'https://api.openai.com/v1/chat/completions'
      : (baseUrl ? `${baseUrl.replace(/\/+$/, '')}/chat/completions` : null);
    if (!url) throw new Error('A base URL is required for an OpenAI-compatible endpoint.');
    return {
      url,
      headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey.trim()}` },
      body: JSON.stringify({
        model: model || 'gpt-4o-mini',
        max_tokens: maxTokens,
        messages: [{ role: 'system', content: system }, { role: 'user', content: prompt }],
      }),
      extractText: (json) => json.choices?.[0]?.message?.content || '',
    };
  }
  throw new Error(`Unknown API provider "${provider}".`);
}
