/**
 * NanoSami nanomaterials reference library.
 * Values are typical literature ranges. Where a property varies strongly with
 * phase, size, morphology, or synthesis, that is stated explicitly.
 * Curated reference data only — user experimental data is never mixed in here.
 */
export default [
  { name: 'Zinc oxide', formula: 'ZnO', class: 'II–VI metal-oxide semiconductor',
    structure: 'Hexagonal wurtzite (most common); zinc blende is rare',
    bandGap: '≈3.3 eV (bulk, direct); increases with strong quantum confinement (<~7 nm)',
    properties: ['Wide direct band gap', 'Large exciton binding energy (~60 meV)', 'Piezoelectric', 'UV absorption', 'Antibacterial activity'],
    synthesis: ['Sol–gel', 'Hydrothermal / solvothermal', 'Co-precipitation', 'Combustion synthesis', 'Green synthesis (plant extracts)'],
    applications: ['UV filters / sunscreens', 'Gas sensors', 'Photocatalysis', 'LEDs and varistors', 'Antimicrobial coatings'],
    characterization: ['XRD', 'FTIR', 'UV–Vis (Tauc plot)', 'SEM/TEM', 'PL spectroscopy'],
    ftir: 'Zn–O lattice stretch ≈420–480 cm⁻¹; surface O–H ≈3430 and H₂O bend ≈1630 cm⁻¹ common.',
    xrd: 'Wurtzite (JCPDS 36-1451): strong (100) ≈31.8°, (002) ≈34.4°, (101) ≈36.3° 2θ (Cu Kα).' },

  { name: 'Titanium dioxide', formula: 'TiO₂', class: 'Metal-oxide semiconductor',
    structure: 'Anatase (tetragonal), rutile (tetragonal), brookite (orthorhombic) — phase depends on synthesis and calcination',
    bandGap: 'Anatase ≈3.2 eV; rutile ≈3.0 eV (both indirect-dominated; varies with doping/size)',
    properties: ['Photocatalytic activity (esp. anatase)', 'High refractive index', 'Chemical stability', 'Non-toxic pigment'],
    synthesis: ['Sol–gel', 'Hydrothermal', 'TiCl₄ hydrolysis', 'Anodization (nanotubes)'],
    applications: ['Photocatalysis / water treatment', 'Dye-sensitized solar cells', 'White pigment', 'Self-cleaning coatings'],
    characterization: ['XRD (phase ID)', 'Raman (anatase 144 cm⁻¹)', 'UV–Vis', 'BET', 'TEM'],
    ftir: 'Broad Ti–O–Ti envelope ≈400–900 cm⁻¹; surface O–H/H₂O bands common.',
    xrd: 'Anatase (101) ≈25.3°; rutile (110) ≈27.4° 2θ (Cu Kα) — used to distinguish phases.' },

  { name: 'Silica', formula: 'SiO₂', class: 'Insulating oxide',
    structure: 'Usually amorphous as nanoparticles (Stöber); crystalline quartz/cristobalite in minerals',
    bandGap: '≈8–9 eV (insulator)',
    properties: ['Chemically inert', 'Easily surface-functionalized (silanes)', 'Mesoporous forms (MCM-41, SBA-15) with high surface area', 'Optically transparent'],
    synthesis: ['Stöber method', 'Sol–gel', 'Microemulsion', 'Templated mesoporous synthesis'],
    applications: ['Drug delivery carriers', 'Chromatography', 'Fillers and abrasives', 'Catalyst supports'],
    characterization: ['FTIR', 'BET', 'TEM/SEM', 'DLS', 'TGA'],
    ftir: 'Si–O–Si asym. stretch ≈1090 (with ≈1200 shoulder), sym. ≈800, rocking ≈465, silanol ≈960 cm⁻¹.',
    xrd: 'Amorphous nanoparticles: broad halo ≈22° 2θ; no sharp reflections.' },

  { name: 'Magnetite', formula: 'Fe₃O₄', class: 'Ferrimagnetic iron oxide (inverse spinel)',
    structure: 'Cubic inverse spinel',
    bandGap: '≈0.1 eV (near-metallic conduction between Fe²⁺/Fe³⁺); often quoted 0.1–2 eV depending on form — verify for your system',
    properties: ['Ferrimagnetic; superparamagnetic below ~20–30 nm', 'Biocompatible (as SPIONs)', 'Fe²⁺/Fe³⁺ mixed valence', 'Oxidizes to maghemite in air'],
    synthesis: ['Co-precipitation (Massart)', 'Thermal decomposition', 'Hydrothermal', 'Solvothermal'],
    applications: ['MRI contrast agents', 'Magnetic hyperthermia', 'Magnetic separation', 'Ferrofluids', 'Water treatment (adsorbents)'],
    characterization: ['XRD', 'VSM/SQUID', 'TEM', 'FTIR', 'Mössbauer (distinguishes from γ-Fe₂O₃)'],
    ftir: 'Fe–O stretch ≈570 cm⁻¹ (plus ≈390 cm⁻¹, often below instrument range).',
    xrd: 'Spinel (311) ≈35.5° 2θ (Cu Kα) strongest; very similar pattern to maghemite — XRD alone may not distinguish them.' },

  { name: 'Hematite', formula: 'α-Fe₂O₃', class: 'Antiferromagnetic (weakly ferromagnetic) iron oxide',
    structure: 'Rhombohedral (corundum type)',
    bandGap: '≈2.1–2.2 eV (indirect); varies with size and doping',
    properties: ['Most stable iron oxide', 'Visible-light absorption (red)', 'Low cost, non-toxic', 'Short hole diffusion length'],
    synthesis: ['Forced hydrolysis', 'Hydrothermal', 'Calcination of other iron (oxyhydr)oxides', 'Sol–gel'],
    applications: ['Photoelectrochemical water splitting', 'Gas sensors', 'Pigments', 'Catalysis'],
    characterization: ['XRD', 'Raman', 'UV–Vis', 'SEM/TEM'],
    ftir: 'Fe–O bands ≈540 and ≈470 cm⁻¹ (positions shift with particle shape).',
    xrd: '(104) ≈33.2° and (110) ≈35.6° 2θ (Cu Kα) are characteristic.' },

  { name: 'Zinc sulfide', formula: 'ZnS', class: 'II–VI semiconductor',
    structure: 'Cubic zinc blende (sphalerite) or hexagonal wurtzite',
    bandGap: 'Zinc blende ≈3.6 eV; wurtzite ≈3.8 eV (direct); increases with quantum confinement',
    properties: ['Wide direct band gap', 'Efficient phosphor host', 'Photoluminescent (dopant-tunable: Mn, Cu)'],
    synthesis: ['Chemical precipitation', 'Hydrothermal', 'Hot-injection (quantum dots)', 'Microwave-assisted'],
    applications: ['Phosphors and EL displays', 'Photocatalysis', 'IR optical windows', 'QD shells (ZnS shell on CdSe)'],
    characterization: ['XRD', 'PL', 'UV–Vis', 'TEM'],
    ftir: 'No strong mid-IR lattice bands in the common 4000–400 cm⁻¹ window; ZnS bands appear near/below ~350 cm⁻¹ — surface species dominate FTIR.',
    xrd: 'Zinc blende: (111) ≈28.6°, (220) ≈47.6°, (311) ≈56.4° 2θ (Cu Kα); nanoparticles give strongly broadened peaks.' },

  { name: 'Cadmium sulfide', formula: 'CdS', class: 'II–VI semiconductor (toxic — handle Cd with care)',
    structure: 'Hexagonal wurtzite (greenockite) or cubic zinc blende',
    bandGap: '≈2.4 eV (bulk, direct); strongly size-dependent in quantum dots (2.4–3+ eV)',
    properties: ['Visible-light absorption (yellow)', 'Strong quantum confinement effects', 'Photocatalytic under visible light', 'Photocorrosion in aqueous media'],
    synthesis: ['Chemical bath deposition', 'Hot-injection', 'Hydrothermal', 'SILAR'],
    applications: ['Quantum dots', 'Photocatalysis (often with co-catalysts)', 'Solar cells (buffer layers)', 'Photodetectors'],
    characterization: ['UV–Vis (size estimation)', 'PL', 'XRD', 'TEM'],
    ftir: 'Cd–S stretch reported ≈600–700 cm⁻¹ region is weak/variable; FTIR mostly shows capping agents — verify against your ligand system.',
    xrd: 'Hexagonal: (100) ≈24.8°, (002) ≈26.5°, (101) ≈28.2° 2θ (Cu Kα).' },

  { name: 'Graphene', formula: 'C (sp², monolayer)', class: '2D carbon',
    structure: 'Single-atom-thick hexagonal carbon lattice',
    bandGap: '0 eV (semimetal); band gap can be engineered in nanoribbons/bilayers',
    properties: ['Exceptional carrier mobility', 'High thermal conductivity', 'Mechanical strength (~1 TPa modulus)', 'Optical transparency (~97.7% per layer)'],
    synthesis: ['Mechanical exfoliation', 'CVD on Cu/Ni', 'Liquid-phase exfoliation', 'Reduction of graphene oxide (gives rGO, defective)'],
    applications: ['Transparent electrodes', 'Sensors', 'Composites', 'Energy storage'],
    characterization: ['Raman (G ≈1580, 2D ≈2700 cm⁻¹; layer number from 2D shape)', 'TEM/AFM', 'XPS'],
    ftir: 'Pristine graphene is nearly IR-featureless; observed bands usually indicate oxygen groups or contamination.',
    xrd: '(002) ≈26.5° 2θ for stacked/graphitic material; true monolayers give no stacking peak.' },

  { name: 'Graphene oxide', formula: 'C with O groups (variable stoichiometry)', class: '2D carbon derivative',
    structure: 'Oxidized graphene sheets with epoxide/hydroxyl on basal plane, carboxyl at edges; interlayer spacing expanded',
    bandGap: 'Insulating to semiconducting (≈1.5–4 eV) depending on oxidation degree — inherently variable',
    properties: ['Hydrophilic, water-dispersible', 'Rich surface chemistry for functionalization', 'Fluorescent', 'Reducible to rGO'],
    synthesis: ['Hummers method (and modified versions)', 'Brodie / Staudenmaier (historical)'],
    applications: ['Membranes', 'Drug delivery', 'Composite fillers', 'Precursor to rGO'],
    characterization: ['FTIR', 'XRD (interlayer spacing)', 'Raman (D/G ratio)', 'XPS (C/O ratio)', 'TGA'],
    ftir: 'O–H ≈3400 (broad), C=O ≈1720, aromatic C=C ≈1620, C–OH ≈1220, C–O (epoxy/alkoxy) ≈1050 cm⁻¹.',
    xrd: '(001) ≈10–11° 2θ (d ≈ 0.8–0.9 nm), vs graphite (002) ≈26.5°; shifts with hydration/oxidation.' },

  { name: 'Carbon nanotubes', formula: 'C (sp², tubular)', class: '1D carbon',
    structure: 'Rolled graphene cylinders; SWCNT (single-wall, ~0.8–2 nm) or MWCNT (multi-wall)',
    bandGap: 'SWCNTs: metallic or semiconducting (0–~1.5 eV) depending on chirality (n,m); MWCNTs typically metallic',
    properties: ['Very high aspect ratio', 'Excellent electrical/thermal conductivity', 'High tensile strength', 'Chirality-dependent electronics'],
    synthesis: ['CVD (most common)', 'Arc discharge', 'Laser ablation'],
    applications: ['Conductive composites', 'Field-emission devices', 'Sensors', 'Energy storage electrodes'],
    characterization: ['Raman (RBM for SWCNT diameter; D/G ratio)', 'TEM', 'TGA (purity)'],
    ftir: 'Weak intrinsic IR activity; bands mainly from functionalization (–COOH ≈1710 cm⁻¹ after acid treatment).',
    xrd: '(002) ≈25–26° 2θ (interlayer of MWCNT walls), broad.' },

  { name: 'Graphitic carbon nitride', formula: 'g-C₃N₄', class: 'Polymeric 2D semiconductor',
    structure: 'Stacked 2D sheets of tri-s-triazine (heptazine) units',
    bandGap: '≈2.7 eV (bulk); tunable by exfoliation/doping',
    properties: ['Metal-free visible-light photocatalyst', 'Thermally stable to ~600 °C', 'Easily synthesized from cheap precursors', 'Moderate surface area unless exfoliated'],
    synthesis: ['Thermal polycondensation of urea / melamine / dicyandiamide (500–580 °C)', 'Exfoliation (thermal/ultrasonic) for nanosheets'],
    applications: ['Photocatalytic H₂ evolution', 'Pollutant degradation', 'CO₂ reduction', 'Sensing'],
    characterization: ['XRD', 'FTIR', 'UV–Vis', 'PL', 'XPS'],
    ftir: 'Sharp ≈810 cm⁻¹ (heptazine breathing), multiple 1200–1650 cm⁻¹ C–N/C=N bands, broad N–H ≈3000–3300 cm⁻¹.',
    xrd: '(100) ≈13.1° (in-plane) and strong (002) ≈27.4° 2θ (interlayer stacking).' },

  { name: 'MXenes', formula: 'Mₙ₊₁XₙTₓ (e.g., Ti₃C₂Tₓ)', class: '2D transition-metal carbides/nitrides',
    structure: '2D sheets from selective etching of MAX phases; surface terminations Tₓ = –O, –OH, –F',
    bandGap: 'Ti₃C₂Tₓ is metallic; some functionalized/ordered MXenes are semiconducting — strongly termination-dependent',
    properties: ['Metallic conductivity', 'Hydrophilic surfaces', 'High volumetric capacitance', 'EMI shielding'],
    synthesis: ['HF or in-situ HF (LiF/HCl) etching of MAX phase', 'Delamination to single flakes', '(HF is extremely hazardous — trained personnel only)'],
    applications: ['Supercapacitors and batteries', 'EMI shielding', 'Sensors', 'Water purification'],
    characterization: ['XRD ((002) shift after etching)', 'SEM (accordion morphology)', 'XPS (terminations)', 'Raman'],
    ftir: 'Bands from surface terminations: O–H ≈3440, Ti–O ≈550–650, C–F region ≈1100 cm⁻¹ — reports vary; verify against recent literature.',
    xrd: 'Ti₃C₂Tₓ: (002) shifts from ≈9.5° (MAX) to ≈6–9° 2θ and broadens after etching/delamination.' },
];
